num1 = int(input("enter a first number: "))
num2 = int(input("enter a second number: "))
num3 = int(input("enter a third number: "))

print(num1+num2+num3)
print(num1-num2-num3)
print(num1*num2*num3)
print(num1/num2/num3)
print(num1+num2-num3)
print(num1-num2+num3)
print(num1*num2/num3)
print(num1/num2*num3)
print(num1+num2*num3)
print(num1-num2/num3)
print(num1+num2/num3)
print(num1-num2*num3)
